# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f27a58b5652fe462c4ec0b024361b0f914ce5f3facac2246bd5fe9cf346773ea1530876ddd2bc752c1a86cf188229dc6c09ad256bb7c7e7e04722f2b07602ac

test:
  secret_key_base: c2d85a0e380a10ca2513653790d82348a37eb2ae6ea9e2fd5a6ce78e39cda00b5581a2ce237e37dfba7b954196fd1fd999ce113054b1c8a47a4cb425558bd602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
